version: '2.3'

networks:
    flask-network:

services:
    flask:
        container_name: p2_exam
        build: .
        environment:
            TZ: America/Sao_Paulo
        ports:
            - "5000:5000"
        networks:
            - flask-network
        volumes:
            - "./:/app"
        mem_limit: 4294965097
        restart: always
        logging:
            options:
                max-size: 100m